---
title: "Lab 03: Data Wrangling"
subtitle: "due Monday, September 14 at 11:59p"
output: 
  tufte::tufte_html:
    css: "sta199-labs.css"
    tufte_variant: "envisioned"
    highlight: pygments
    toc: true
    toc_depth: 1
link-citations: yes
editor_options: 
  markdown: 
    wrap: sentence
---

# Goals

In this lab, you will...

- Use data wrangling to extract meaning from data
- continue developing a workflow for reproducible data analysis.

# Getting started

-   Go to the [**sta199-fa21-003**](https://www.github.com/sta199-fa21-003) organization on GitHub. Click on the repo with the prefix **lab-03**. It contains the starter documents you need to complete the lab.

- Clone the repo and start a new project in RStudio. See the [Lab 01 instructions](https://sta199-fa21-003.netlify.app/labs/lab-01-hello-r.html) for details on cloning a repo and starting a new R project.

# The Greatest Crossover Event in the History of STA199 Labs

We will also load the `tidyverse` package as usual.

```{r load-packages, message = FALSE}
library(tidyverse)
```

This data was originally collected for a [FiveThirtyEight](https://fivethirtyeight.com/features/avengers-death-comics-age-of-ultron/) piece. The version of the `avengers` data we will work with here can be uploaded from the `avengers.csv` file provided with this lab. This dataset covers the entire Marvel Cinematic Universe(MCU), so some of the names will be familar if you are a fan of the filmes, while other might be from the comics. Don't worry if you aren't a Marvel fan though, no background knowledge is needed to succeed on this lab!

More information on the variables is available at this link [this link](https://github.com/fivethirtyeight/data/tree/master/avengers).

1. You are interested in creating a dataset with the most "classic" Avengers. Using `filter`, create a new dataset with only Avengers that were created 1) in 1970 or earlier and 2) were not given probationary status. You should call the new dataset `classic_avengers`. 

*Now would be a good time to knit, commit, and push.*

2. Who are the newest Classic Avengers? Using `mutate`, please create a new variable called `years_served` that represents the number of years served **as of 2021.** (Hint: you can use either the `year` variable or `years_since_joining` variables to do this.) Then, please arrange the dataset in *ascending* order of `years_served`, select the `Name/Alias` and `years_served` variables and print the first three rows using `slice`. Report in words the names of the three newest Classic Avengers and how long they have served. Please do this using a single pipeline.

3. Has the percentage of female Avengers changed much over time? Using `summarize` find the percentage of female Avengers in the `classic_avengers` dataset and compare it to the percentage of all female Avengers. Please describe in words what you observe. (Hint: before using `summarize`, in the same pipeline you should create a new numeric variable that will allow you to find the percentage of female Avengers.)

*Now might be a good time for another knit, commit, and push.*

4. Arrange the overall `avengers` dataset in descending order of `appearances` and return only the columns `Name/Alias`, `Appearances`, `Death1`, and `Return1`. Slice the first five Avengers here. What do you notice about these Avengers in terms of deaths and returns?

5. Using the `avengers` dataset `group_by()` and `summarize()` to examine the mean and median number of appearances for Avengers who have died at least once compared to those who *have not* died at least once. What do you learn about Marvel movies from your results? Also, does this tell you anything about the mean and median?

*One more exercise, but first, knit, commit, and push!*

6. Are newer or older Avengers more popular? Create a scatterplot of the mean appearances by year of introduction for Avengers. Add `geom_smooth()` with the argument `se = FALSE`. Please include informative axis labels and an informative title. Can you observe any trends in the data? Which years tend to have the Avengers with the most appearances? Briefly explain whether you need to use any caution in interpreting any portions of this graph.

Once you are fully satisfied with your lab, **Knit to PDF** to create a PDF 
document.

Follow the instructions in previous labs to submit your PDF to Gradescope.

Be sure to identify which problems are on each page using Gradescope.

# Grading

Overall: 50 pts.

- Exercise 1: 5 pts
- Exercise 2: 8 pts
- Exercise 3: 6 pts
- Exercise 4: 4 pts
- Exercise 5: 7 pts
- Exercise 6: 8 pts
- Overall:  8 pts
  - Overall includes the number of commits made, naming chunks, updating the name on the assignment to your name, and following tidyverse style (see: https://style.tidyverse.org/). 